/* Stockback shelf: brands that pay in their own tokenized stock on Robinhood Chain */
(function(root){
var SHELF = [
  {name:"Costco",ticker:"COST",domain:"costco.com",rate:2,cat:"Groceries",proof:["paper"],settle:212,price:914.2,note:"Warehouse till receipt"},
  {name:"Apple",ticker:"AAPL",domain:"apple.com",rate:3,cat:"Electronics",proof:["paper","email"],settle:184,price:232.1,note:"Store receipt or order email"},
  {name:"Amazon",ticker:"AMZN",domain:"amazon.com",rate:2,cat:"Retail",proof:["email"],settle:236,price:214.7,note:"Order confirmation email"},
  {name:"Whole Foods",ticker:"AMZN",domain:"wholefoodsmarket.com",rate:2,cat:"Groceries",proof:["paper"],settle:251,price:214.7,note:"Pays in Amazon"},
  {name:"Netflix",ticker:"NFLX",domain:"netflix.com",rate:3,cat:"Subscription",proof:["email"],settle:171,price:1187.4,note:"Monthly renewal email"},
  {name:"Lululemon",ticker:"LULU",domain:"lululemon.com",rate:4,cat:"Clothing",proof:["paper","email"],settle:298,price:201.5},
  {name:"Hims & Hers",ticker:"HIMS",domain:"hims.com",rate:4,cat:"Health",proof:["email"],settle:207,price:52.3},
  {name:"Roblox",ticker:"RBLX",domain:"roblox.com",rate:4,cat:"Games",proof:["email"],settle:163,price:128.9,note:"Robux and Premium"},
  {name:"Reddit",ticker:"RDDT",domain:"reddit.com",rate:3,cat:"Subscription",proof:["email"],settle:190,price:224.6,note:"Reddit Premium"},
  {name:"Rivian",ticker:"RIVN",domain:"rivian.com",rate:1,cat:"Motoring",proof:["email"],settle:344,price:13.1,note:"Service and charging"},
  {name:"Take-Two",ticker:"TTWO",domain:"take2games.com",rate:4,cat:"Games",proof:["email"],settle:201,price:238.4,note:"GTA, NBA 2K, Zynga"},
  {name:"AMC Theatres",ticker:"AMC",domain:"amctheatres.com",rate:4,cat:"Cinema",proof:["paper","email"],settle:176,price:3.02,note:"Odeon in the UK"},
  {name:"GameStop",ticker:"GME",domain:"gamestop.com",rate:3,cat:"Games",proof:["paper"],settle:224,price:23.8},
  {name:"Xbox",ticker:"MSFT",domain:"xbox.com",rate:2,cat:"Games",proof:["email"],settle:158,price:512.6,note:"Game Pass, pays in Microsoft"},
  {name:"Microsoft 365",ticker:"MSFT",domain:"microsoft.com",rate:2,cat:"Subscription",proof:["email"],settle:166,price:512.6},
  {name:"YouTube Premium",ticker:"GOOGL",domain:"youtube.com",rate:2,cat:"Subscription",proof:["email"],settle:181,price:242.7,note:"Pays in Alphabet"},
  {name:"Google One",ticker:"GOOGL",domain:"google.com",rate:2,cat:"Subscription",proof:["email"],settle:179,price:242.7},
  {name:"Ray-Ban Meta",ticker:"META",domain:"meta.com",rate:3,cat:"Eyewear",proof:["paper","email"],settle:266,price:748.2,note:"Sold by opticians"},
  {name:"Tesla",ticker:"TSLA",domain:"tesla.com",rate:1,cat:"Motoring",proof:["email"],settle:302,price:388.5,note:"Supercharging and service"},
  {name:"Dell",ticker:"DELL",domain:"dell.com",rate:2,cat:"Electronics",proof:["email"],settle:241,price:132.4},
  {name:"AliExpress",ticker:"BABA",domain:"aliexpress.com",rate:3,cat:"Retail",proof:["email"],settle:288,price:161.9,note:"Pays in Alibaba"},
  {name:"Coinbase",ticker:"COIN",domain:"coinbase.com",rate:2,cat:"Fees",proof:["email"],settle:149,price:318.7,note:"Trading fees on a filled order"},
  {name:"Nike",ticker:"NKE",domain:"nike.com",rate:4,cat:"Clothing",proof:["paper","email"],soon:true},
  {name:"McDonald's",ticker:"MCD",domain:"mcdonalds.com",rate:3,cat:"Food",proof:["paper"],soon:true},
  {name:"Uber",ticker:"UBER",domain:"uber.com",rate:2,cat:"Travel",proof:["email"],soon:true},
